services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "5555:5555" # Expose port for Prisma Studio
    volumes:
      - ./backend:/app 
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/florabit
    depends_on:
      - db

  db:
    image: postgres:15.13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: florabit
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
